# Generated by Django 5.1.1 on 2024-10-07 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateField(blank=True, default=datetime.datetime.now)),
                ('body', models.CharField(max_length=1000)),
            ],
        ),
    ]
